### ISSUE TITLE
Compatibility Issue with pandas==2.2.0 and to_offset('Q') Function

### ISSUE THREAD

**Issue by nmharmon8** [time-series-foundation-models/lag-llama#1]
# Summary:
Encountered an incompatibility issue with pandas==2.2.0 where using to_offset('Q') raises an exception for "invalid frequency". This functionality works as expected in pandas==2.1.4. Suggesting an update to the requirements to specify the pandas version to ensure compatibility.

# Steps to Reproduce:
Set up a Docker container with dependencies specified in the requirements file, which defaults to using pandas==2.2.0.
Execute the following Python code:

```python
from pandas.tseries.frequencies import to_offset
to_offset('Q')
```

# Observe the raised exception.
Expected Behavior:
The to_offset('Q') call should correctly interpret 'Q' as a quarterly frequency without raising an exception.

# Actual Behavior:
When running with pandas==2.2.0, the code raises the following exception:

```python
raise Exception("invalid frequency")
```

**Comment by ashok-arjun** [comment]
Hi @nmharmon8, yes, this is a well known issue with pandas 2.2.0 since the [aliases for the frequencies have changed in pandas 2.2.0](https://pandas.pydata.org/docs/whatsnew/v2.2.0.html#deprecate-aliases-m-q-y-etc-in-favour-of-me-qe-ye-etc-for-offsets).

Thanks for letting us know! I'll update the requirements file with the right pandas version.
