### ISSUE TITLE
just about time

### ISSUE THREAD

**Issue by rainbownmm** [time-series-foundation-models/lag-llama#21]
Thanks for such a great open source work. I feel so excited. I can’t wait to ask how long it will take to update the code for fine-tuning and training，You can close this issue at any time, it's just a little complaint from those who are waiting.

**Comment by ashok-arjun** [comment]
Apologies, we've been held up with other submissions after our release.

We're working on the finetuning code now, and will release it soon (sorry, cannot give an estimate of the time since we can run into unexpected issues when we make a colab demo).

I'll update here once we release it. 

Thanks for the patience!

**Comment by kashif** [comment]
@rainbownmm check fine-tuning demo https://colab.research.google.com/drive/1uvTmh-pe1zO5TeaaRVDdoEWJ5dFDI-pA?usp=sharing

**Comment by rainbownmm** [comment]
Thanks
