### ISSUE TITLE
Timeseries with multi-column data

### ISSUE THREAD

**Issue by eftymakr** [time-series-foundation-models/lag-llama#35]
Hello. Thank you so much for the open-source implementation.
I have a custom dataset with cryptocurrency values for daily prediction which except from the target values, 
includes also 3 columns of related features. 
Those columns could be included in your implementation? Are features taken into account from the model or is just the target value?

**Comment by smrnvdhy** [comment]
(Not a dev). Lag llama doesn't support features mostly due to the nature of foundation models. They're trained on a large body of data sets and supposed to be able to do inference on any data. Both the training and use case data may or may not have varying number of features, including none, so features are not included on purpose.

**Comment by ashok-arjun** [comment]
Hi @eftymakr. Lag-Llama unfortunately does not support covariates (which are features apart from the target value, as you have). Currently, you can only use the historical values of the target variable to predict for future values of the target variable. 

Thanks @smrnvdhy for  pointing out the difficulty of building a foundation model that can support arbitrary number of covariate features. It could in fact be possible to use features in a foundation model if it's trained to perform inference with and without features, and trained to work well with additional features specific to your own data. Building such a model is an open research question in my opinion.

**Comment by ashok-arjun** [comment]
Closing this issue. Feel free to open it if required :)
