### ISSUE TITLE
Question about forecast_it

### ISSUE THREAD

**Issue by hugogobato** [time-series-foundation-models/lag-llama#5]
I noticed that the dimensions of the output of the first term in the list of:

`forecast_it, ts_it = make_evaluation_predictions(
    dataset=backtest_dataset,
    predictor=predictor,
)`

is always (100, prediction_length), at least with the example and when using my own dataset, independent of the length of the test data length. Am I right here? Is this a bug? If not, how should I interpret the 100?

This the link to the Jupyter Notebook used for my own dataset https://drive.google.com/file/d/1WThIccnVKq_V48bC2FzmdzvHLEquLK94/view?usp=sharing

Kind Regards,

Hugo

**Comment by hugogobato** [comment]
This a link to the Jupyter Notebook used for my own dataset https://drive.google.com/file/d/1WThIccnVKq_V48bC2FzmdzvHLEquLK94/view?usp=sharing

**Comment by kashif** [comment]
Since its a probabilistic forecaster, the 100 refers to the samples from the predicted distribution per time-step. Also note that the model weights provided were specifically trained over a subset of the datasets available, in order to do the analysis for the paper. We will add a fine-tuning script so that folks are able to train on even more diverse datasets with the hope that they also share the weights.

**Comment by hugogobato** [comment]
Dear @kashif, thank you very much for the answer! One last question: if I would like to perform forecasts using a test dataset composed of 1000 datapoints and using prediction_length = 10 (i.e., I want to perform the forecasts 100 times), is there an easy way to perform such multiple-step forecasts using Lag-LLama?

**Comment by ashok-arjun** [comment]
Hi @hugogobato, our current inference is the way you describe (multi-step, each step sampling 100 samples).

**Comment by ashok-arjun** [comment]
Hi @hugogobato, is this clarified? Can I close the issue?

**Comment by hugogobato** [comment]
@ashok-arjun, yes, thank you!

**Comment by hugogobato** [comment]
Yes, thank you!
