### ISSUE TITLE
problem dataset weather and mae metric

### ISSUE THREAD

**Issue by m6129** [time-series-foundation-models/lag-llama#60]
Hello, Dear Developer
Can I know if you have performed any operations on dataset **weather**, before feeding it into the model, [I am getting an error](https://colab.research.google.com/drive/127GCKakWloOSMmbNWlrkoRciRV-R7VZ1?usp=sharing)
`TypeError: object of type 'NoneType' has no len()`

I also wanted to ask your advice, if it doesn't take a lot of your attention, if you could tell me how to calculate the MAE metric
Thanks

**Comment by ashok-arjun** [comment]
Hi,

Is the problem with the weather dataset solved, I can look into the error if it's not resolved.

As for the MAE metric, we do not recommend it in fact, since we did not design our model with point-forecasting in mind. However, if you'd like to compute it for a paper/report, you could use the MAE value returned by the GluonTS Evaluator along with other metrics, or using the mean of the probabilistic forecast and then computing MAE, or using the median of the probabilistic forecast and then computing MAE (you can try the 3 methods and choose the one with the best average MAE, since we do not provide any "default" way to compute MAE/give point-predictions). I request that you indicate that our model was meant for probabilistic forecasting, in case you report any point-forecasting metric.
