### ISSUE TITLE
Can the model make predictions for a column of data without a time feature

### ISSUE THREAD

**Issue by ympppppp** [time-series-foundation-models/lag-llama#90]
Can the model make predictions for time series without time features, i.e., autoregressive predictions

**Comment by ashok-arjun** [comment]
The pretrained model - not by design, but there are workarounds - you'd have to add a start date to your dataset, and select a dummy frequency to increment the date in. You could test different start dates and frequencies.

If you are pre-training a model from scratch, you can remove the time features and pretrain it.

**Comment by ympppppp** [comment]
> The pretrained model - not by design, but there are workarounds - you'd have to add a start date to your dataset, and select a dummy frequency to increment the date in. You could test different start dates and frequencies.
> 
> If you are pre-training a model from scratch, you can remove the time features and pretrain it.

Thank you so much for your helpful advices
